name: Artillery Playwright Test

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Artillery
        run: npm install -g artillery

      - name: Install Playwright
        run: npm install -g playwright

      - name: Install dependencies
        run: npm install

      - name: Run Artillery Playwright test
        run: |
          artillery script C:\Users\Mario\Desktop\demo\artillery.yml

      - name: Save Artillery Report
        uses: actions/upload-artifact@v2
        with: 
            name: artillery-report
            path: artillery-report/
          
      - name: Display Artillery Report
        uses: actions/github-script@v4
        with:
            script: | 
                const fs = require('fs');

                const reportPath = `${process.env.RUNNER_WORKSPACE}/artillery-report/report.json`;
                const reportData = fs.readFileSync(reportPath, 'utf8');
        
                console.log(reportData);


      